### ISSUE TITLE
--convert-to-managed option may not be working

### ISSUE THREAD

**Issue by adhishrajgupta** [microsoft/powerplatform-vscode#106]
We are utilizing Powerplatform CLI v1.9.4+gbda9f20 in our project to build a CI and release pipeline for deployment of solutions. I noticed that I am not able to make the --convert-to-managed option to work. My goal was to import an unmanaged solution into an upstream environment and convert it to a managed solution. Here are examples of the command that I am using -
pac solution import -ap -a -cm -p "C:\Users\adhishgupta\Downloads\my_unmanaged.zip"

OR
pac solution import -p "C:\Users\adhishgupta\Downloads\my_unmanaged.zip" --async --convert-to-managed

Each time, the solution is imported as unmanaged successfully but not converted to managed. Am I missing something or is there a bug?

**Comment by davidjenni** [comment]
@adhishrajgupta the convert-to-managed parameter on ImportSolution is poorly and confusingly named, it does NOT achieve what you're intending to do: to convert an unmanaged solution to a managed solution.

Your approach insofar is correct that only the Dataverse environment can convert from unmanaged to managed. But the right approach is as follows:
- if the unmanaged solution is not yet part of the target environment, import the unmanaged solution into the currently selected/connected environment, with a ```pac solution import -p my_unmanaged.zip``` incantation similar to yours, but remove the ```--convert-to-managed``` parameter
- then export the solution, but specify to export it as managed:
```pac solution export --name my_solution_name --path somefolder --async --managed```
this will export your solution as somefolder\my_solution_name_managed.zip

more info:
https://docs.microsoft.com/en-us/power-platform/alm/move-from-unmanaged-managed-alm

3b Export the unmanaged solution(s) from your development environment as **managed**. More information: Export solutions

**Comment by adhishrajgupta** [comment]
Thanks @davidjenni for the clarification.
