### ISSUE TITLE
"pac paportal download" downloads non adx... table

### ISSUE THREAD

**Issue by adekola** [microsoft/powerplatform-vscode#110]
Hi team, 

While downloading a Portal using the CLI, I noticed a non adx table (Note [annotation]) was downloaded together with the rest of the contents. 

See below
![133046469-0e87b1e5-a73b-4c76-849a-e36ec1befaa5](https://user-images.githubusercontent.com/2733967/133047690-8ad36711-5e8a-4674-b1cc-92717e99aa67.png)

This presents a challenge for scenarios when a customer wants to download the config of a PROD portal in order to move this to a DEV environment as part of setting up an ALM process.

Could this unexpected behavior be investigated

**Comment by ameyaapte1** [comment]
The thought behind including annotations is to not end up breaking adx_webfile records, the tool will not download all annotation but only those which are related to the webfiles of the current website. If we skip downloading all annotation and a user uploads this data to a different org, this destination org will be missing the required annotations (css, images etc) and the portal will not function properly

**Comment by ashishchoudhary001** [comment]
Hi @adekola, I hope the previous comment answers your query. I am closing this case, please feel free to re-open or log another case in case there are any more queries.
