### ISSUE TITLE
What does "pac solution version" do?

### ISSUE THREAD

**Issue by adhishrajgupta** [microsoft/powerplatform-vscode#116]
How and when is the pac solution version command supposed to be used? The documentation on that is very sparse so will appreciate any guidance on that.

**Comment by davidjenni** [comment]
@adhishrajgupta ```pac solution version``` purpose is to mutate the patch version in a local solution.xml file (result of an extracted/unpacked solution.zip in the local file system).

It has 4 strategies to increment the patch part of the major.minor.patch triple found in solution.xml.
All follow the same flow:
1. determine from the "version persistence" the last assigned patch version
2. increment it by 1
3. mutate/update the local solution.xml in the local git repo's file system
4. store new version back into that "version persistence":

The 4 different version persistence strategies are:
- git tags: last assigned version is assigned a git tag in the local repo and pushed to the remote/origin repo
- filetracking: creates and maintains a local .csv file (needs to be saved and/or committed to git repo)
- solution: directly use the version triple found in the solution.xml
- directly use a CI/CD system's build id variable, e.g. for [Azure DevOps: Build.BuildId](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services) with the ```--patchversion``` parameter
