### ISSUE TITLE
Error creating Admin profile for UsGov cloud instance

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-vscode#127]
i am trying to add admin profile for our UsGov instance and it keeps erroring out with this error message.

![image](https://user-images.githubusercontent.com/3292092/138124511-651391fb-bb9d-4a0c-b8f2-8085e694eec3.png)

Here is the command i ran:
`
 auth create -k ADMIN -ci UsGov
`

**Comment by davidjenni** [comment]
@sanjeev40084 yes, pac CLI's sovereign cloud support, including matching pre-Authorizations for our client ids, is missing. This has been worked on in the last several weeks, and we'll soon (end of year) will be releasing a pac CLI with proper sovereign cloud support

**Comment by sanjeev40084** [comment]
@davidjenni this issue can be closed now. With version 1.11.3, I no longer get this error message.
