### ISSUE TITLE
Error using in codespace or wsl

### ISSUE THREAD

**Issue by feng-huang** [microsoft/powerplatform-vscode#133]
I use the pac command in VS Code(with extension installed) in a CodeSpace, the command failed.
1. Use on the url,  failed with below
Error: Unable to open a web page using xdg-open, gnome-open, or kfmclient tools. See inner exception for details. Possible causes for this error are: tools are not installed or they cannot open a URL. Make sure you can open a web page by invoking from a terminal: xdg-open https://www.bing.com 
Failed to locate a utility to launch the default web browser.

2. Use url + correct username/password, always got auth failed, do we need to install additional package on linux?
Error: AADSTS50126: Error validating credentials due to invalid username or password.
Trace ID: f927415e-9ca9-4d21-8cb8-835ed52bda00
Correlation ID: 0a88d6ef-34bc-415b-a7d0-b46258423b0c
Timestamp: 2021-11-02 09:58:35Z

**Comment by tehcrashxor** [comment]
WSL:
By default, most Linux distro images used in WSL do not have any GUI tools installed, including the ability to launch web browsers for the interactive Auth flows.  It looks like we haven't yet documented that anywhere, but the `Error: Unable to open a web page using xdg-open, gnome-open, or kfmclient tools` message indicates the missing prereq for those flows.  For the default Ubuntu image used by WSL, this can be handled by running `sudo apt install xdg-utils`, which then handles the request to open the web browser for the auth flow.

CodeSpaces, SSH, and other non-WSL Remoting:
Currently, the VS Code extension and the underlying PAC process cannot handle the interactive auth flow, even if that system has the bits to handle launching the browser window for authentication.  The underlying MSAL auth library launches the browser and runs a small web server on `localhost:[RandomPort]` for the AAD login flow to redirect to after successful authentication.  Unfortunately, the `localhost` running the VS Code Extension and PAC is the remote machine, not your local machine hosting the web browser, so the redirect will not hit correct machine, preventing the completion of the Auth flow.
We're looking into solutions for those remote scenarios, but do not have anything concrete yet.

**Comment by feng-huang** [comment]
Thanks, yes, using the WSL locally will work. So even if we are specifying the username/password in the pac command, it will still using the this Auth flow which will not work on remote scenario right, such as Codespace.

pac auth create [--name] [--kind] [--url] **[--username] [--password]** [--applicationId] [--clientSecret] [--tenant] [--cloud]

**Comment by davidjenni** [comment]
> Thanks, yes, using the WSL locally will work. So even if we are specifying the username/password in the pac command, it will still using the this Auth flow which will not work on remote scenario right, such as Codespace.
> 
> pac auth create [--name] [--kind] [--url] **[--username] [--password]** [--applicationId] [--clientSecret] [--tenant] [--cloud]

@feng-huang correct, when running pac CLI on GH CodeSpaces, it is running remotely, which makes the interactive authN form impossible.
The only way to authenticate is via the explicit username/password parameters. But if your PowerPlatform credentials required ConditionalAccess verification like 2FA/MFA etc., that will still not succeed, since AAD will (correctly) insist you to verify the additional MFA.
Then your option is to use the SPN/appID approach, similar to other headless/non-interactive environments as on Github Actions workflow runners and Azure DevOps build agents.
Yes, this is indeed cumbersome, but the lack of interactive login flows is a current limitation of the remote execution model that GH Codespaces has.
https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools#configure-service-connections-using-a-service-principal

**Comment by tehcrashxor** [comment]
With the release of [PAC v1.12.2](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.12.2) and the [VS Code Extension v0.2.35](https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.powerplatform-vscode), PAC now supports Device Code login.
This supports interactive login for MFA or ADFS Federated tenants on remote installations of PAC such as GH CodeSpaces.

To use, just call `pac auth create` with the `--deviceCode` switch, without a username + password or applicationId parameters, and you will be given a Device Code and login URL to pull up in a browser such as:
![image](https://user-images.githubusercontent.com/3751389/155241512-73eef5a8-066e-4bab-81ef-45fe414c53f0.png)
Complete the auth flow in the browser, and the PAC CLI will create the auth profile.
