### ISSUE TITLE
PLEASE HELP!!! Issues with Power Platform Tools

### ISSUE THREAD

**Issue by jswiger88** [microsoft/powerplatform-vscode#136]
I recently installed “Power Platform Tools” into Visual Studio Code. I was able to download all of my project files and settings from my portal apps. However, when I am trying to upload the changes that I have made, I am getting this error. “ Updating table adx_webpage with record id:a77ec5d4-9236-ec11-b6e6-00224824282b FAILED due to A validation error occurred.  The length of the 'adx_summary' attribute of the 'adx_webpage' entity exceeded the maximum allowed length of '2000'. “

**Comment by ameyaapte1** [comment]
This error is being thrown as the maximum limit on the length of the adx_summary column is set to 2000 characters in Dataverse by deafult. The restriction can be removed by changing the maximum length of the Summary column on the entity adx_webpage.

Steps to fix this would be:
* Go to make.powerapps.com 
* Under Data go to Tables
* Select Webpage entity, click on the Summary column
* On right side pane expand the advanced options and scroll down
* Change the Max Length to the desired number
