### ISSUE TITLE
Execution status is not set by pac

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#137]
When a pac command fails it should be possible to detect via the last execution variable, e.g $? (https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.2#section-1) in PowerShell, similar in bash.

This is currently not working.  See example below:

![image](https://user-images.githubusercontent.com/6078398/142067576-d83fb092-2071-4141-a9cb-f31b079ad8b1.png)

**Comment by davidjenni** [comment]
in your PS prompt, are you calling the pac.exe directly, or is it via the pac.cmd that the MSI installer is using?
Please try:
```
Get-Command pac
```

On my machine (Win or macOS), the exit status makes it properly to the $? auto var, e.g.:
```
> pac solution list
Microsoft PowerPlatform CLI
Version: 1.9.9+g8a4823f

Error: No profiles were found on this computer. Please run 'pac auth create' to create one.


Usage: pac solution list [--environment-id]

  --environment-id            The target Environment ID.  Default value is the environment of your currently active Dataverse Auth Profile.

> $?
False

> pac help
<snip>

> $?
True
```

**Comment by filcole** [comment]
Here's what I'm getting - the difference between us is that I'm using an expired profile, it looks like no profiles are configured in your example.

![image](https://user-images.githubusercontent.com/6078398/145210725-f264a42b-7ef6-4739-aa1a-5d4eb50f027e.png)

**Comment by davidjenni** [comment]
@filcole ah, your repro is specific to pac not properly reflecting the expired auth profile/token as a non-zero exist status. I'm filing a bug in our pac CLI backlog.

**Comment by davidjenni** [comment]
tracked as bug 2541444 in our internal DB

**Comment by davidjenni** [comment]
just checked, this is still pending getting fixed
AB#2541444

**Comment by davidjenni** [comment]
@filcole this has been fixed with other changes we made to the auth module (to support sovereign clouds), confirmed in latest 1.14.2, but also as far as 1.11.8:

```
> pac solution list
Microsoft PowerPlatform CLI
Version: 1.11.8+gb7437cd

Error: You are trying to use expired authentication profile. Please either switch to different profile or delete and recreate the profile again.


Usage: pac solution list [--environment] [--environment-id]

  --environment               The target Environment ID or URL.  Default value is the environment of your currently active Dataverse Auth Profile. (alias: -env)
  --environment-id            (deprecated) The target Environment ID.  Default value is the environment of your currently active Dataverse Auth Profile.

(23:05:38) ~\Src\pp-vscode [main ≡]
> $?
False
```

**Comment by filcole** [comment]
Great news - thanks @davidjenni
