### ISSUE TITLE
--allowDelete has wrong instruction in the help section

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-vscode#144]
Based on the help command in pac module, if you want to unpack solution, this is the instruction you get i.e.
--allowDelete               Dictates if delete operations may occur [Yes|No]; default: No. (alias: -ad)

![image](https://user-images.githubusercontent.com/3292092/147699203-0eec8f1f-bdfa-45fe-8fe3-c993fda92dc4.png)

However, if you try to run the unpack command with the value of 'Yes' or 'No' in --allowDelete flag, it errors out with this error message:
![image](https://user-images.githubusercontent.com/3292092/147699298-369711f2-1cc1-46ee-b6bc-e9d6eeb2be3f.png)

if you run the same command with true/false boolean value, i.e. --allowDelete true or --allowDelete false, the command runs successfully. The solution unpack help instruction needs to be updated.

To replicate the issue:
1. Run this command:
`
pac solution unpack help
`
2. Check the help instruction for '--allowDelete' flag. It should display this:
![image](https://user-images.githubusercontent.com/3292092/147699541-2b3afed3-c242-48f6-83a9-48e8046e4acf.png)

3. Export managed solution from Power platform makers portal
4. Run this command to unpack the solution based on the instruction displayed from step 1. 
`
pac solution unpack --zipfile [--folder] --packagetype 'managed' --allowDelete 'No'
`
4. You should get this error message:
![image](https://user-images.githubusercontent.com/3292092/147699298-369711f2-1cc1-46ee-b6bc-e9d6eeb2be3f.png)

**Comment by davidjenni** [comment]
tracked as AB#2649785

**Comment by davidjenni** [comment]
fixed in our main branch, AB#2649785 is resolved. Will be part of the next monthly refresh
