### ISSUE TITLE
List of solutions is not possible on Dataverse for Teams

### ISSUE THREAD

**Issue by megel** [microsoft/powerplatform-vscode#147]
The command `pac solution list` fails on Dataverse for Teams.

Command:
```
pac solution list --environment-id <my-teams-environment-id>
```

Result:
```
Connected to...Team My Teams-Team
Listing all Solutions from the current Dataverse Organization...
Microsoft PowerPlatform CLI
Version: 1.10.4+gf23be2f

Error: The 'RetrieveOrganizationInfo' is only allowed to be accessed from OData endpoint in Dataverse for Teams offering. EnitytName: none
```

**Comment by davidjenni** [comment]
@megel  this is likely by design, given how Dataverse for Teams works. Will clarify internally

**Comment by petrochuk** [comment]
It looks like you are using pac 1.10.4. Please try new version 1.14 (run "pac install latest") which has almost all fixes for Teams environments. Version 1.15 will also enable backup/restore functionality.
