### ISSUE TITLE
Add UniqueName as column when listing environments

### ISSUE THREAD

**Issue by orangetoken** [microsoft/powerplatform-vscode#161]
It would be very useful to get the uniqueName of the Dataverse environment when executing "pac admin list". 

UniqueName has the form of "org*" or "unq*" and is still used in many places. For example when reviewing the installed D365 Marketing applications which have the UniqueName instead of the environment guid.

**Comment by davidjenni** [comment]
@orangetoken we're taking this under consideration, and if approved, we'll apply the same logic to `pac org list`

while the code change in pac CLI is trivial in itself, the challenge is we're already showing too many columns, resulting in an unwieldy long text line per env

**Comment by davidjenni** [comment]
@sanjeev40084 your proposed syntax would work if the pac CLI were a PS module, which it is not for the time being.

Note that in recent pac CLI releases (1.16.x or newer?), `pac org list` does include a column w/ the unique name as well
