### ISSUE TITLE
Power Apps Portal editing - Liquid in JS is flagged as errors

### ISSUE THREAD

**Issue by weshutton** [microsoft/powerplatform-vscode#178]
When you include Liquid tags in javascript when editing a portal advanced form step, the liquid tags cause multiple errors to be displayed:

![image](https://user-images.githubusercontent.com/25720530/160216249-ab5e74a4-634d-460f-924e-dd31fc9acec5.png)

**Comment by ameyaapte1** [comment]
Syntax highlighting is a vscode feature, To resolve the errors you are facing you can install a third party plugin for liquid syntax highlighting

**Comment by neerajnandwana-msft** [comment]
This is specific to the liquid code, and it can be resolved by using third party VSCode plugins.

**Comment by ameyaapte1** [comment]
Closing the issue as per Neeraj comment
