### ISSUE TITLE
Unpack fails with error

### ISSUE THREAD

**Issue by DaveStabilify** [microsoft/powerplatform-vscode#188]
ERROR RETURNED: Error: An item with the same key has already been added.

PS C:\Users\Dave> cd "F:\OneDrive - Stabilify, LLC\PowerApp Projects\Packages\CaseworkerHub-v713-COPY_20220415195828\Microsoft.PowerApps\apps\10012562781360855322" 
PS F:\OneDrive - Stabilify, LLC\PowerApp Projects\Packages\CaseworkerHub-v713-COPY_20220415195828\Microsoft.PowerApps\apps\10012562781360855322> pac canvas unpack --msapp N2d96f620-b358-4fdf-aaa5-7d4c43f720d9-document.msapp --sources "F:\OneDrive - Stabilify, LLC\PowerApp Projects\Packages\CaseworkerHub-v713-COPY_20220415195828\Microsoft.PowerApps\apps\10012562781360855322\Extract"
Warning: canvas unpack is in preview, and functionality is not guaranteed. Use extreme caution if using in a production environment. For more information see aka.ms/paccanvas
UnPack from F:\OneDrive - Stabilify, LLC\PowerApp Projects\Packages\CaseworkerHub-v713-COPY_20220415195828\Microsoft.PowerApps\apps\10012562781360855322\N2d96f620-b358-4fdf-aaa5-7d4c43f720d9-document.msapp-->F:\OneDrive - Stabilify, LLC\PowerApp Projects\Packages\CaseworkerHub-v713-COPY_20220415195828\Microsoft.PowerApps\apps\10012562781360855322\Extract
Microsoft PowerPlatform CLI
Version: 1.14.2+g7205df7

Error: An item with the same key has already been added.

**Comment by davidjenni** [comment]
@DaveStabilify this is likely an issue within the Canvas serialization library

```
pac canvas unpack --msapp N2d96f620-b358-4fdf-aaa5-7d4c43f720d9-document.msapp --sources ...
```

Can you provide the .msapp for the owner of that library to try and repro, then fix?
N2d96f620-b358-4fdf-aaa5-7d4c43f720d9-document.msapp

Feel free to send the .msapp to PPTools@microsoft.com , I can relay to the owning team

CC: @navneetThekkumpat
