### ISSUE TITLE
Find out whether a Solution is Managed or Unmanaged

### ISSUE THREAD

**Issue by p3pijn** [microsoft/powerplatform-vscode#190]
I'm looking to export all unmanaged Solutions from a given environment in an automated way.
When doing `pac solution list` this gives me a list of all solutions.
However, there seems to be no way currently to find out which Solutions are managed or unmanaged.
This is an issue because managed Solutions can not be exported.

Would it be possible to add a flag to the `pac solution list` command? E.g. for `--unmanaged` to only return the list of unmanaged solutions?

**Comment by davidjenni** [comment]
this was added several releases ago, resolving:
![image](https://user-images.githubusercontent.com/3200210/197078583-381855b8-18d0-4cb7-bf16-62fccc06d97d.png)

**Comment by rajyraman** [comment]
@p3pijn - I have been using below in PowerShell.

```powershell
pac solution list --json | ConvertFrom-Json | Where-Object { $_.IsManaged -eq $false } | Sort-Object -Property FriendlyName
```
