### ISSUE TITLE
Improve commands exit code for scripting

### ISSUE THREAD

**Issue by nmedda** [microsoft/powerplatform-vscode#193]
**Description**

`pac auth select -n ...` always return True

I'm creating scripts to help manipulate my solutions in a multi developer setup.
But when I select my authentication, it always returns true.

```PowerShell
PS > pac auth select -n NonExistingAuth
Microsoft PowerPlatform CLI
Version : 1.14.2+g7205df7

Erreur : Il n'existe aucun profil d'authentification portant le nom « NonExistingAuth »

Utilisation : pac auth select [--index] [--name]

  --index                     Index du profil à activer (alias : -i)
  --name                      Nom du profil à activer (alias : -n)
PS > $?
True
```

So I need to catch this error somehow, to make sure were not importing a solution if we're not targeting the expected environement.

**Suggestion**

Return a non zero value if there is no authentication profile that matches the requested name

P.S. : And thanks a ton for your amazing work with pac ;)

**Comment by petrochuk** [comment]
Fixed in 1.15.1
