### ISSUE TITLE
VSCode extension does not allow renaming of auth profiles > 12 characters

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#198]
The CLI allows profiles to be renamed up to 30 characters long, whereas the VSCode extension still has input validation which limits the profile length to 12 characters.  Occurs in extension version v1.0.9

![image](https://user-images.githubusercontent.com/6078398/168427535-17ea76c3-b66d-4330-83e2-782252ec7d0b.png)

The problem seems to be here:
https://github.com/microsoft/powerplatform-vscode/blob/54cda378abcfd9f4d5829acf6efb0ef339618996/src/client/lib/PacActivityBarUI.ts#L72 and in the localised error messages

The simple workaround is to use the CLI directly, e.g. `pac auth name --index 10 --name 12345678901234567890`

**Comment by tehcrashxor** [comment]
Interesting, looks like the VS Code side validation matches the validation help text from PAC, but the PAC side validation is in fact 30 characters,.

Tracking as AB#2724005

**Comment by tehcrashxor** [comment]
The fix has been rolled out in v1.0.16
