### ISSUE TITLE
Add command to set security group of instance during create or reset of instance

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-vscode#200]
We have a need where we need to reset the instance and install the master solution every once in a while. With current pac command, most of the stuff can be automated except for setting security group of the instance. Since the security group cannot be set while running reset command, the service account that is being used to automate the process loses access after the reset is complete because of missing security group. It would be nice to set the security group during the process of reset of instance so that when the instance comes back after reset, the service account won't lose access and can perform other tasks against the environment. Same request during the creation of the new instance.

example:

`
pac  admin reset -env [URL or ID] -security-group-id [AD-Group-Guid-ID]

**Comment by filcole** [comment]
Noticed in pac 1.17.4 there's now a `--team-id` option in `pac admin create`.  Might this help?

**Comment by sanjeev40084** [comment]
@filcole
don't think it adds the security group, atleast it didn't for mine.

![image](https://user-images.githubusercontent.com/3292092/184912841-11a08dd9-7022-44d7-b50b-16d5c954e9b0.png)

![image](https://user-images.githubusercontent.com/3292092/184913122-4ccdbbe2-323a-4913-95f0-f15a150aafad.png)

**Comment by sanjeev40084** [comment]
@filcole  i believe you might be right.
