### ISSUE TITLE
Error: ************ Exception getting metadata info from Dataverse   : Failed to resolve entity metadata for adx_blog.

### ISSUE THREAD

**Issue by nick626262** [microsoft/powerplatform-vscode#255]
Can't download portal data using Version: 1.17.4+g2bdb4f2 

I get error :

Error: ************ Exception getting metadata info from Dataverse   : Failed to resolve entity metadata for adx_blog.

I don't have adx_blog in my dataverse environment. I am using starter portal 9.3.2204.69. 

Reverting to the previous version of the extension works.

**Comment by ameyaapte1** [comment]
We have caught this in our test pipelines, it will get hotfixed soon, till then you can revert to the previous version of pac cli to use the paportal commnad.
@davidjenni @ashishchoudhary001 @neerajnandwana-msft

**Comment by nick626262** [comment]
Thanks - glad you're on it.

**Comment by khoait** [comment]
I have the same error today

**Comment by khoait** [comment]
It's working for me with the updated CLI. Thanks!

**Comment by ashishchoudhary001** [comment]
Closing this issue as it has been hotfixed.
