### ISSUE TITLE
Percentage complete for async operations never reaches 100%

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#262]
Follow on from #194 the percentage complete does not reach 100% for async import/export/publish operations, e.g.

It also seems that the precision could be reduced!  Note: The percentages reported by package deployer are correct.   Here's an example below.

```text
Connected to...Phil Cole's Environment
Starting Solution Export...
Waiting for asynchronous operation 59c58e13-0d1b-ed11-b83e-000d3adaf6ec to complete with timeout of 01:00:00
Processing asynchronous operation... execution time: 00:00:00 and 0.00658618888888889% complete
Processing asynchronous operation... execution time: 00:00:04 and 0.123488905555556% complete
Processing asynchronous operation... execution time: 00:00:08 and 0.239268244444444% complete
Processing asynchronous operation... execution time: 00:00:13 and 0.367193177777778% complete
Processing asynchronous operation... execution time: 00:00:17 and 0.484886027777778% complete
Processing asynchronous operation... execution time: 00:00:21 and 0.601410858333333% complete
Processing asynchronous operation... execution time: 00:00:25 and 0.717828608333333% complete
Processing asynchronous operation... execution time: 00:00:30 and 0.834186822222222% complete
Asynchronous operation 59c58e13-0d1b-ed11-b83e-000d3adaf6ec successfully finished within 00:00:34.2398031
```

**Comment by davidjenni** [comment]
this is currently by design: it's a simple percentage until timeout is reached.

The DV API gives clients no progress reporting when the client queries for completion of  the async operation. Even for operations like import solution where pac CLI knows e.g. the size, there is just no way to even guestimate the service progress until done.

**Comment by filcole** [comment]
@davidjenni I'm confused how the package deployer manages to report a percentage complete that goes from 0 to 100%.  Similarly I can query the `importjob` table and look at the progress field and watch it increase from 0 to 100%.
