### ISSUE TITLE
pac admin assign-user doesn't work with alias

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-vscode#269]
if you try to run 'pac admin assign-user' command and use -env and -u alias, it errors out with following error message. 

![image](https://user-images.githubusercontent.com/3292092/185445004-d6c6a5fc-4b86-49f1-a9f9-bcb1b6fd31c1.png)

however If you use the full argument name it works.
![image](https://user-images.githubusercontent.com/3292092/185445386-995b5704-2e4c-4af2-8c27-71c6a4d4aa49.png)

**Comment by tehcrashxor** [comment]
The short aliases only use a single `-`, and your screenshot above shows that you used two: `--env` and `--u`
