### ISSUE TITLE
IntelliSense for PowerFx

### ISSUE THREAD

**Issue by miguelverweij** [microsoft/powerplatform-vscode#275]
To bridge the gap between pro and low-code, it would be nice if IntelliSense can do suggestions for PowerFx code. Especially now that effort is put into the git integration.

**Comment by jblankenspoor** [comment]
Nice one @miguelverweij!

**Comment by davidjenni** [comment]
To go beyond syntax coloring and actual Intellisense/completion for PowerFx requires semantic knowledge that is currently not easily accessible outside of maker studio.
It would indeed be a cool feature to add, but it is not on the short term roadmap

CC: @kkanakas @MikeStall

**Comment by Hjaf** [comment]
Could this be re-opened? 

I have no idea where to start implementing it, but considering that we have official grammar (both for pure [expressions](https://github.com/microsoft/Power-Fx/blob/main/docs/expression-grammar.md) and [yaml](https://github.com/microsoft/Power-Fx/blob/main/docs/yaml-formula-grammar.md) ) along with access to [interpreter](https://github.com/microsoft/Power-Fx/tree/main/src/libraries/Microsoft.PowerFx.Interpreter) source code, would it be sufficient for implementing it?

https://github.com/microsoft/Power-Fx/blob/main/docs/overview.md
