### ISSUE TITLE
"pac pcf push" for v1.18.4 doesn't update the PCFs

### ISSUE THREAD

**Issue by brasov2de** [microsoft/powerplatform-vscode#294]
Hello, 
I'm using the latest pac v1.18.4. "pac pcf push" doesn't update the PCFs. Or at least, it doesn't publish properly.
The workarround found until now:
 - publishAll after "pac pcf push"
 - alternatively downgrade to version v1.16.6 - that one works
There are some reports on the community forum too: https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Virtual-PCF-Dataset-Component-Not-Getting-Update/m-p/1778857#M6824

**Comment by davidjenni** [comment]
We're investigating on our end. To summarize current reported issues:
- pcf push seems to fail for virtual field only, but works for virtual dataset?
- issue reproes with pac CLI 1.18.4 (latest) and 1.17.7 (July refresh), but still works with 1.16.6

**Comment by brasov2de** [comment]
Hi  @davidjenni , 
I've made a few more tests. The issue occurs:
- for both standard and virtual components
- for both field and dataset components
- it doesn't publish with 1.18.4 and 1.17.5, but it works with 1.16.6
- manually PublishAll after "pac pcf push" solves the issue.

I had a better look to the stuff written in the console. It seems pretty clear that the latest pac  doesn't publish.


**Here are the logs from 1.18.4 (after import there is no publish message)**

![image](https://user-images.githubusercontent.com/29977935/192846796-78f11b87-400b-405e-b72a-49581e0686e2.png)

**And here are the logs from 1.16.6 (there is a "Publish All Customizations"):**

![image](https://user-images.githubusercontent.com/29977935/192846974-47016af7-7182-4d95-b003-73a662a0a386.png)

**Comment by brasov2de** [comment]
I've tested with the pac cli v1.19.3, and it still doesn't work.
"pac pcf push" will upload the component, but I need a "PublishAll" inside my environment (or "pac solution publish"), in order to see the changes inside my app.

**Comment by davidjenni** [comment]
@brasov2de we've finally got a consistent repro, and found the regression. We have now a fix ready that we'll ship as QFE later this week

AB#2959078

**Comment by brasov2de** [comment]
I've just confimed that the issue git fixed with the pac cli version 1.19.4. Thank you so much!
