### ISSUE TITLE
'Unable to find assembly registration configuration' issue. pac solution sync and building cdsproj with plugins causing error.

### ISSUE THREAD

**Issue by RajeevPentyala** [microsoft/powerplatform-vscode#309]
Tested the powerplatform-vscode-1.1.3 build.

**Steps to reproduce:**
- Cloned a Dataverse solution with plugin assemblies and other components using 'pac solution clone'.
![image](https://user-images.githubusercontent.com/104883923/194804954-9b9ccf0c-faf7-4273-81ae-da071df08d38.png)

- Unpacked folders had ‘PluginAssemblies’ and ‘Pluginpackages’ folders.
- Added plugin .csproj file to .cdsproj using 'pac solution add-reference' command
- Added more Dataverse components and synced the same Dataverse solution with plugin assemblies using 'pac solution sync' command.
- ‘PluginAssemblies’ and ‘Pluginpackages’ folders were removed from local unpacked folders.
- Built the .cdsproj using "msbuild /t:build /restore" command
- Got following error
_.\.nuget\packages\microsoft.powerapps.msbuild.solution\1.18.4\build\Microsoft.PowerApps.MSBuild.Solution.targets(102,5): error : **Unable to find assembly registration configuration** for  ..\source\repos\cat-f
usion\Accounts\Plugins\cat.plugins\bin\Debug\net462\Cat.Plugins.dll in the destination: obj\Debug\Metadata\PluginAssemblies [D:\PAC\VSIX\Accounts\Accounts.cdsproj]
Done Building Project ..\Accounts\Accounts.cdsproj" (build target(s)) -- FAILED.__

**Comment by mannybellas** [comment]
@RajeevPentyala just wanted to see what was done to resolve this bug? Is it resolved in a later version of `pac`?
