### ISSUE TITLE
pac canvas unpack

### ISSUE THREAD

**Issue by SashiPanigrahi** [microsoft/powerplatform-vscode#313]
I am trying to unpack canvas file from a downloaded msapp file but not able to do so.
![image](https://user-images.githubusercontent.com/85726346/195997523-c91b8903-7c7d-40eb-82fc-d160657fd4c9.png)
![image](https://user-images.githubusercontent.com/85726346/195997599-c50cf846-51ab-49e3-8750-7d653b871f89.png)

can you please let me know where i am going wrong ?

**Comment by davidjenni** [comment]
@SashiPanigrahi you're missing the `unpack` verb in 3 of your incantations, and the error message is unfortunately somewhat misleaded ("Unneeded argument was passed").

The CLI expects this overall structure: `pac` <noun> <verb> <parameter/argument pairs>, i.e. for your repro:

`pac canvas unpack --msapp c:\Users\sashi\Downloads\HiringManagementApp.msapp --sources d:\Solution\CanvasApps\unpacked`
