### ISSUE TITLE
Pac paportal download reverse manifests records order at each execution

### ISSUE THREAD

**Issue by ThierryBIENVENU** [microsoft/powerplatform-vscode#321]
I don't know if this is the right place to ask the problem but every time I run the following command in the vscode terminal :
`pac paportal download --path '.' --webSiteId 'xxx' --overwrite`
then the records in the .portalconfig/org-manifest.yml and .portalconfig/manifest.yml files are rewritten in the reverse order of the previous execution.
It forces me to rerun the command before committing files to avoid unintelligible diff in commit history.

**Comment by MrRishabhJain** [comment]
Yes, I have verified this behavior, running download the second time eliminates the inadvertent diff. As this is not ideal, we will look into this issue.

**Comment by MrRishabhJain** [comment]
This issue has been fixed and will be shipped as a part of our upcoming release in January.

**Comment by MrRishabhJain** [comment]
@ThierryBIENVENU, the fix has been released with Power Platform Tools v1.1.16.

**Comment by ThierryBIENVENU** [comment]
Thanks @MrRishabhJain for the follow-up.
I've tested v1.1.16 and the manifiest is more stable but there are new component with DisplayName $RELATIONSHIP$adx_webpageaccesscontrolrule:<guid> and $RELATIONSHIP$adx_entitypermission:<guid> which change order now at each download.
Oddly, even if there no change, cheksum change. See capture 
![image](https://user-images.githubusercontent.com/107684640/218719170-3a7b1b12-7f98-4e8b-ada0-3cc625ae43dc.png)

**Comment by MrRishabhJain** [comment]
@ThierryBIENVENU, Thanks for bringing this scenario to our attention, seems like sorting records beyond the record ID is required here. Will update here once this fix is released.

**Comment by MrRishabhJain** [comment]
Hey @ThierryBIENVENU, we had resolved this issue and the manifest should be generating successfully now, can you please confirm?

**Comment by ThierryBIENVENU** [comment]
Hello @MrRishabhJain, Nice to hear, the manifest is much more stable now and generates less noise during commit.
Great job.
