### ISSUE TITLE
`pac solution unpack --allowDelete --processCanvasApps` will delete canvas app source if run a second time

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#334]
The allowDelete and processCanvasApps flags on pac solution unpack seem incompatible.  With a solution that contains a canvas app, e.g. a model driven app with a new Power Fx component library, then the first unpack will process and expand the solution and associated canvas app (.msapp) correctly.  If the same command is run again the files in CanvasApps\src\\* are deleted.

## First Unpack

```text
❯ pac solution unpack --folder PacSolutionUnpackCanvas --allowDelete --processCanvasApps --zipfile .\PacSolutionUnpackCanvas_1_0_0_1.zip

Unpacking Solution...

Extracting C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas_1_0_0_1.zip to C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas

Skipping localization
Processing Component: Entities
 - pgc_PrimeMinister
Processing Component: EntityRelationships
Processing Component: AppModuleSiteMaps
 - pgc_PrimeMinisterApp
Processing Component: AppModules
 - pgc_PrimeMinisterApp
Processing Component: CanvasApps
 - pgc_primeministerappdefaultcommandlibrary_b5677

-- unpacking Canvas app pgc_primeministerappdefaultcommandlibrary_b5677...
Unpack from C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas\CanvasApps\pgc_primeministerappdefaultcommandlibrary_b5677_DocumentUri.msapp --> C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas\CanvasApps\src\pgc_primeministerappdefaultcommandlibrary_b5677
  source format version: 0.24

Unmanaged Extract complete.


Unpacked Solution.
```

![image](https://user-images.githubusercontent.com/6078398/198907730-c6fc590c-8a7b-4ed8-978e-7c967fb67522.png)

## Second Unpack

```text
❯ pac solution unpack --folder PacSolutionUnpackCanvas --allowDelete --processCanvasApps --zipfile .\PacSolutionUnpackCanvas_1_0_0_1.zip

Unpacking Solution...

Extracting C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas_1_0_0_1.zip to C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas

Skipping localization
Processing Component: Entities
 - pgc_PrimeMinister
Processing Component: EntityRelationships
Processing Component: AppModuleSiteMaps
 - pgc_PrimeMinisterApp
Processing Component: AppModules
 - pgc_PrimeMinisterApp
Processing Component: CanvasApps
 - pgc_primeministerappdefaultcommandlibrary_b5677

-- unpacking Canvas app pgc_primeministerappdefaultcommandlibrary_b5677...
Unpack from C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas\CanvasApps\pgc_primeministerappdefaultcommandlibrary_b5677_DocumentUri.msapp --> C:\Users\...snip...\allowDelete\PacSolutionUnpackCanvas\CanvasApps\src\pgc_primeministerappdefaultcommandlibrary_b5677
  source format version: 0.24

Unmanaged Extract complete.


There are 18 unnecessary files
Deleting files...

Unpacked Solution.
```

Notice 18 unnecessary files reported and deleted! Checking the file system we can see the canvas apps source files have been deleted. 😱

![image](https://user-images.githubusercontent.com/6078398/198907776-097115c1-bffa-4d6f-a68e-91a693a869d6.png)

Here's the solution zip used for testing.  It contains a table 'Prime Minister', a 'Prime Minister App', a component library adding a 'Replace Incumbent' button to the main form on the 'Prime Minister' table.

[PacSolutionUnpackCanvas_1_0_0_1.zip](https://github.com/microsoft/powerplatform-vscode/files/9897073/PacSolutionUnpackCanvas_1_0_0_1.zip)

**Comment by mikefactorial** [comment]
Looks to be the same issue as here https://github.com/microsoft/powerplatform-build-tools/issues/135

**Comment by RobNightingale-LSL** [comment]
I also have this issue

**Comment by RobNightingale-LSL** [comment]
@filcole did you try the following flag in the build task in the advanced section?
`OverwriteFiles: false` 

This looks, from my testing, to add/remove 2 parameters, one being the offender!:
`--allowDelete true`
`--allowWrite true`

The defaults for both these parameters are false so has potential, but feels counter intuitive to turn off allowWrite.

**Comment by filcole** [comment]
No.  I experienced the issue when using `pac` directly in a PowerShell script.  I'm not sure what the PPBT ADO tasks are issuing, but I think you can normally see in the logs.

**Comment by petrochuk** [comment]
Fixed in latest versions of PAC CLI and other libraries
