### ISSUE TITLE
NPM packages Release Notes

### ISSUE THREAD

**Issue by BetimBeja** [microsoft/powerplatform-vscode#358]
Hi @davidjenni,
the version on the latest release notes for `pcf-scripts` and `pcf-start` doesn't look right. It is 0.1.0:
![image](https://user-images.githubusercontent.com/11160171/202651952-2eafeae9-0f5e-489c-97fb-82afad8da7fd.png)

**Comment by davidjenni** [comment]
yep, bug, will be fixed in Nov refresh 1.21.x
