### ISSUE TITLE
`pac modulebuilder build` code generated by 'Unknown Title' (Unknown Version)

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#362]
When testing `pac modulebuilder build` with the following 

`pac modelbuilder build --writesettingsTemplateFile --namespace ACME.Entities --serviceContextName ServiceContext --emitfieldsclasses --entitynamesfilter "account;contact" --suppressGeneratedCodeAttribute --outdirectory EntityModel2 --suppressINotifyPattern true`

I notice the Code Generated by comment says Unknown Title (Unknown Version). see below

![image](https://user-images.githubusercontent.com/6078398/202886496-abf5376f-da27-4541-ae33-7e16748e3cc8.png)

Also, it's lacking space after the `//` on that line, so might fall foul of some linting rules. (editorConfig)

**Comment by MattB-msft** [comment]
This has been corrected and will be published as part of the next patch.

**Comment by MattB-msft** [comment]
This has been fixed in PAC CLI 1.21.8
