### ISSUE TITLE
`pac modulebuilder build` doesn't generate method summary comments in the `EntityOptionSetEnum.cs` file

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#363]
I noticed a minor nit when using pac modulebuilder as below:

`pac modelbuilder build --writesettingsTemplateFile --namespace ACME.Entities --serviceContextName ServiceContext --emitfieldsclasses --entitynamesfilter "account;contact" --suppressGeneratedCodeAttribute --outdirectory EntityModel2 --suppressINotifyPattern true`

Nit: The method documentation is not generated in the `EntityOptionSetEnum` file, whereas it's added to on most (all?) other methods in other files.

![image](https://user-images.githubusercontent.com/6078398/202886676-29a7d0bd-4ed0-481c-8933-dbdce49a11d3.png)

**Comment by MattB-msft** [comment]
This has been corrected and will be published as part of the next patch.

**Comment by MattB-msft** [comment]
This has been Added in PAC CLI 1.21.8
