### ISSUE TITLE
`pac modulebuilder build` generates lowercase enums 

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#364]
When using the following command to generate earlybound classes

I *think* that the enums generated are incorrect, because they're all lowercase.  I think they should be Pascal case, as generated by the XrmToolbox EarlyBoundGenerator (and I think crmsvcutil).  My assumption is that the logical name is being used, instead of the schema name.

In the screenshot below, the left side is created via pac modulebuilder, the right side via the XrmToolbox EBG.

![image](https://user-images.githubusercontent.com/6078398/202887042-a63a52c8-54ca-45ae-ba99-9a053613bcc9.png)

**Comment by MattB-msft** [comment]
The name reflected there is the name of the object in the system itself, which is in lowercase. 
In the case of that particular item, the display name is actually "Role" (in English), which would result in a Contact_Role if the display name was used to create the property name.  In this case the behavior was not changed from CrmSvcUtil to the Dataverse Model builder. . 

We try to stay away from localized names and are cleaning up spots in the code where localized name was used (where we can) to avoid the localization issues.  

In the above case, I believe the Xrmtoolbox EBG has a feature that attempts to camel case values that are not camel cased. 

Going to not fix this one unless it becomes a breaking issue down the road.

**Comment by filcole** [comment]
Understood.  That's the most obvious (and quite painful) reasons that will stop me migrating existing projects from EBG to `pac modulebuilder build`.  It's amazing the amount of stuff that's in the EBG naming service now properly investigate: 

For future reference:
https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/blob/166e832ff988e7da30e0757d77342fb09d4d32ca/DLaB.CrmSvcUtilExtensions/NamingService.cs

The generated code feels quite a bit less like C# should "feel", due to the casing not matching the normal c# coding conventions.
