### ISSUE TITLE
`pac modelbuilder build` Problem with `Settings Template File`

### ISSUE THREAD

**Issue by BetimBeja** [microsoft/powerplatform-vscode#373]
> `--settingsTemplateFile` `-stf`
> Contains Settings to be used for this run of the Dataverse Model Builder, overrides any duplicate parameters on command line. Cannot be set when --writesettingstemplate is used.

My Understanding is that the `Settings Template File` should override duplicate parameters from the command line.

So, the order of precedence for each parameter should be:
- settingsTemplateFile
- command line
- default value

The problem I am facing is a `NullReferenceException` when the `Settings Template File` does not contain all required properties. Example JSON that throws the exception:

```json
{
  "entityNamesFilter": [
    "account"
  ]
}
``` 
Exception details:
```
C:\Users\Betim>pac modelbuilder build -o test -stf test\builderSettings.json
Microsoft PowerPlatform CLI
Version: 1.20.3+ga66a744

Error: Model generation failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.BuilderSettings.SettingsParser.AddOrSkipAddingProperty[T](List`1& argList, SettingsConfiguration incommingArray, String settingName, String targetpropertyname)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.BuilderSettings.SettingsParser.ReadSettingsFileIntoArgs(String[] incomingArgs)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ModelBuilderInvokeParameters.LoadArguments(String[] args)
   at bolt.module.modelbuilder.verbs.ModelBuilderVerb.Execute(IContext context, Command command)
```

**Comment by filcole** [comment]
Hi @BetimBeja, I can't help about the crash, but I'm wondering if that's the correct precedence for the flags.  I'd be expecting:
    command line flags
    settings file
    default

i.e. for command line flags to take preference over the settings file

**Comment by BetimBeja** [comment]
❤️ @filcole while I might expect the same about the flags 😄 I was just interpreting the statement from the tool documentation:

> ...overrides any duplicate parameters on command line. 

You can't help with the crash because Microsoft owns the tool? or because you don't get the error message if you try the same?

**Comment by MattB-msft** [comment]
This fix has been shipped.  Cleaning threads.
