### ISSUE TITLE
Problem with pac cli in VSCode on MacOS

### ISSUE THREAD

**Issue by JurgenPostelmans** [microsoft/powerplatform-vscode#387]
Hi,

The Power Platform CLI used to just run fine on my MacBook Pro until a couple of weeks ago. When I now type pac and hit enter it just seems to *hang*. Even pressing Ctrl-C does not bring me back at the command prompt. After 4-5 minutes the command eventually will run and show the available commands. 

I've uninstalled/reinstalled .NET but still the behavior stays the same. 

Jurgen

**Comment by petrochuk** [comment]
Try installing pac cli with new `dotnet tool`
