### ISSUE TITLE
Managed Identity does not work in lot of situations

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-vscode#401]
When I create a connection with Managed Identity, it seems I cannot use it for lot of the commands.

_pac solution list_
![image](https://user-images.githubusercontent.com/5035266/210292103-14868e84-17ec-45ab-8c3e-10f9ea97e7f0.png)

_pac modelbuilder build_
![image](https://user-images.githubusercontent.com/5035266/210292134-8fdb5e8e-56f5-46ca-90ce-6a502c4b83fa.png)

_pac solution publish_
![image](https://user-images.githubusercontent.com/5035266/210292165-80875e7e-863e-4dc7-9974-60a4eb26d7e6.png)

I can create new connections with Managed Identity and use the Az CLI credentials seamlessly, but the inability to use it is a blocker. Is this new capability only for Az DevOps Pipelines?

![image](https://user-images.githubusercontent.com/5035266/210292326-114bbd14-0994-4f64-9813-40cdd7f955e6.png)

cc @kkanakas

**Comment by kkanakas** [comment]
It is only for Azure DevOps.
As I have stated here 
https://powerapps.microsoft.com/en-us/blog/power-platform-developer-tools-november-update/
![image](https://user-images.githubusercontent.com/22942069/210297288-52fb74d2-fca7-4fdf-b695-0c64245b4f57.jpeg)

**Comment by rajyraman** [comment]
@kkanakas - If this is only for AzDO, please add a blurb on the help as it does seem like a valid choice because it can create connections.

![image](https://user-images.githubusercontent.com/5035266/210298678-3734ab73-b016-492a-b4e3-f1d6a7170aa3.png)

I have been using Azure Identity Framework for getting token to Dataverse environments for a while now and it works seamlessly. Considering that there are a lot of Power Apps devs who are also working in Azure, why not add this a choice for people to interact with Dataverse in their local machine using PP CLI? It is so much easier than filling in username password on the OAuth2 popup.
