### ISSUE TITLE
Bug: Solution import timeout shown as import failed

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-vscode#416]
When solution import is still in progress, pac exits with solution import failure error when the solution import is still continuing in the background. Solution import timeout should not be characterised as import failure.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/5035266/212593515-d4ee8836-015d-4011-b65c-d4924dcf7641.png">

**Comment by petrochuk** [comment]
It looks like default 1 hour timeout
