### ISSUE TITLE
`pac plugin init` Plugin template Logger purpose?

### ISSUE THREAD

**Issue by skfd** [microsoft/powerplatform-vscode#444]
There is this attribute that I don't understand the purpose of. How should it be used? Can you please document it in the summary?

Also note there is an extra space after `get;  `

```
        /// <summary>
        /// ILogger for this plugin.
        /// </summary>
        ILogger Logger { get;  }
```

Thank you!

**Comment by mannybellas** [comment]
Plugins can log to Application Insights via this interface:

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/application-insights-ilogger

**Comment by skfd** [comment]
nice! would be nice to link to this article from template
