### ISSUE TITLE
Error: ************ Exception getting metadata info from Dataverse   : Failed to resolve entity metadata for adx_websitelanguage.

### ISSUE THREAD

**Issue by k-harrington** [microsoft/powerplatform-vscode#448]
Can't download portal data using Version: 1.21.8+ga93a2c3

I get error :

Error: ************ Exception getting metadata info from Dataverse   : Failed to resolve entity metadata for adx_websitelanguage.

Will try previous version. 1.21.5

**Comment by MrRishabhJain** [comment]
Hi @k-harrington. Thanks for reaching out. Can you please share the logs present in the `<PAC install location>/tools/logs`.

Also, let us know if you are able to download this portal using an older version on PAC CLI.

**Comment by MrRishabhJain** [comment]
Hey @k-harrington, closing this thread for now. If you still face the issue, feel free to re-open this. Thanks!
