### ISSUE TITLE
Allow specifying a custom install path in the MSI Installer

### ISSUE THREAD

**Issue by martintoelk** [microsoft/powerplatform-vscode#477]
Hi PAC CLI Team,

in big cooperations, there might be some ploicy that only allows installing software into specfic folders. The msi installer does not allow to to select a install directory. It would be great, if one could select a different install folder in the msi installer.

BR

Martin

**Comment by petrochuk** [comment]
Take a look at new way of installing using `dotnet tool` which allows installing PAC CLI into custom locations [here](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-power-platform-cli-for-windows)
