### ISSUE TITLE
no response when clicking on ""add auth profile" button

### ISSUE THREAD

**Issue by afei2046** [microsoft/powerplatform-vscode#487]

**Comment by tehcrashxor** [comment]
Which OS and version are you encountering this on?
If using macOS or Linux, do you have the required net6.0 installed?
If using an Apple Silicon / M1 / M2 arm64, do you have both the x64 and arm64 versions of net6.0 installed?

In some cases, the Auth dialog (Windows) or Auth webpages (Linux & Mac) open up _behind_ the VS Code window.  Is that occurring in your case?
