### ISSUE TITLE
pac modelbuilder - generateActions and messagenamesfilter inconsistencies 

### ISSUE THREAD

**Issue by drivardxrm** [microsoft/powerplatform-vscode#495]
I'm trying to generate early-bound classes for some custom apis using pac modelbuilder and i'm getting weird results.

It might be related to issue #413 

1- If I only put the --generateActions switch without any message filtering 
You can see that for 935 messages found on the environment, only 217 are written.
Is that normal behavior?
![image](https://user-images.githubusercontent.com/38399134/229385898-58ce5b16-8dca-4709-9d34-1c56f668d9ef.png)

2- Obviously I don't want to generate classes for all these actions and I want to filter the messages using --messagenamesfilter.  I want only one action called 'driv_GetEnvironmentVariable'. Note that this class was generated when I ran the unfiltered command so I know its present on my environment.

When I run this, it doesn't find it and no messages/actions are written to the output directory, 
![image](https://user-images.githubusercontent.com/38399134/229386211-5bd353db-030b-45eb-912b-191fc3b9dc61.png)

3-More strange, if I put a wildcard filter using my publisher name, I get all the actions from my publisher and the action I wanted on the previous call is found
![image](https://user-images.githubusercontent.com/38399134/229386543-164d21f7-3542-4f72-a211-d2dc0bae5765.png)

Also If I check all the actions that are generated, I get CreateMultiple.cs and UpdateMultiple.cs generated even if there were supposed to be filtered out
![image](https://user-images.githubusercontent.com/38399134/229386759-b358200e-5b37-4ac2-8536-ab88d03238c7.png)

Am I doing something wrong?

**Comment by drivardxrm** [comment]
Following a recommendation from @daryllabar ,
It seems that by adding a wildcard '*' at the end of every desired actions it works well

--messagenamesfilter "driv_GetEnvironmentVariable*"

I still get the CreateMultiple and UpdateMultiple class created though. 

![image](https://user-images.githubusercontent.com/38399134/229550603-0b619f6e-b769-426c-8204-10bfeac2eee5.png)

Is this a bug or the desired behavior of the tool ?

**Comment by SimonFindling** [comment]
Can confirm this behaviour.
Also it seems like if you add an messagefilter and entityfilter at the same time and the message filter isn't valid also your entities are not created:
````
pac modelbuilder build --outdirectory . --messagenamesfilter "something" --entitynamesfilter "account" --generateActions                          
Verbunden mit ... 2G Energy DEV
Verbunden als crmAdmin@2-g.de
Begin Reading Metadata from MetadataProviderService
        Begin Reading Metadata from Server
        Read 1 Entities
        Read 0 Global OptionSets
        Read 0 SDK Messages
        Completed Reading Metadata from Server - 00:00:00.9556870
Completed Reading Metadata from MetadataProviderService - 00:00:00.9575475
Begin Writing Code File
        Processing 1 Entities
        Wrote 0 Entities - 00:00:00.0027674
        Processing 0 Messages
        Wrote 0 Messages - 00:00:00.0000061
        Processing 0 Global OptionSets
        Wrote 0 Global OptionSets - 00:00:00.0000090
Completed Writing Code File - 00:00:00.0067981

````
as you can see above "account" entity is not created with message filter "something". This also doesn't work with valid message names:
````
pac modelbuilder build --outdirectory . --messagenamesfilter "msdyn_DeleteCalendar" --entitynamesfilter "account" --generateActions
Verbunden mit ... 2G Energy DEV
Verbunden als crmAdmin@2-g.de
Begin Reading Metadata from MetadataProviderService
        Begin Reading Metadata from Server
        Read 1 Entities
        Read 0 Global OptionSets
        Read 0 SDK Messages
        Completed Reading Metadata from Server - 00:00:00.8938379
Completed Reading Metadata from MetadataProviderService - 00:00:00.8951303
Begin Writing Code File
        Processing 1 Entities
        Wrote 0 Entities - 00:00:00.0021953
        Processing 0 Messages
        Wrote 0 Messages - 00:00:00.0000057
        Processing 0 Global OptionSets
        Wrote 0 Global OptionSets - 00:00:00.0000064
Completed Writing Code File - 00:00:00.0056367

````
as example I tried to create the [msdyn_DeleteCalendar](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/msdyn_deletecalendar?view=dataverse-latest) action which gives the same result.

Only with the workaround mentioned by @drivardxrm it works as (hopefully) intended:
````
pac modelbuilder build --outdirectory . --messagenamesfilter "msdyn_DeleteCalendar*" --entitynamesfilter "account" --generateActions
Verbunden mit ... 2G Energy DEV
Verbunden als crmAdmin@2-g.de
Begin Reading Metadata from MetadataProviderService
        Begin Reading Metadata from Server
        Read 1 Entities
        Read 0 Global OptionSets
        Read 10 SDK Messages
        Completed Reading Metadata from Server - 00:00:32.1627109
Completed Reading Metadata from MetadataProviderService - 00:00:32.1641759
Begin Writing Code File
        Processing 1 Entities
        Wrote 1 Entities - 00:00:00.0705926
        Processing 10 Messages
        Wrote 3 Messages - 00:00:00.0160334
        Processing 10 Global OptionSets
        Wrote 10 Global OptionSets - 00:00:00.0024262
        Code written to xxx\Entities\account.cs.
        Code written to xxx\Messages\msdyn_DeleteCalendar.cs.
        Code written to xxx\Messages\CreateMultiple.cs.
        Code written to xxx\Messages\UpdateMultiple.cs.
        Code written to xxx\OptionSets\msdyn_travelchargetype.cs.
        ...
Completed Writing Code File - 00:00:00.1242477

````
I don't think messagefilter should affect entityfilter at all.

**Comment by daryllabar** [comment]
Message filter is a different bug.  Put asterisks at the end of your messages and that should work, or use the latest version of the Early bound generator V2

**Comment by MattB-msft** [comment]
Folks.. .sorry for the long delay here, 
We shipped a fix for Model builder to resolve the issue with messages not being picked up correctly without the * on them.
current versions of PAC CLI have this update. 

That should resolve this issue, and i am going to close this one. 

There is a separate issue with very dense environment's ( ~800+ entities ) that is causing messages to be missed, which we will track under #413.  We are working on that too.
