### ISSUE TITLE
Issue with MacOS and pac

### ISSUE THREAD

**Issue by Laskewitz** [microsoft/powerplatform-vscode#50]
When running the pac command in the terminal (happens both in zsh & pwsh) in VS Code, I get the following error:

![error](https://user-images.githubusercontent.com/3766843/119800777-61099580-bedd-11eb-8200-82e6cb9c62b6.jpg)

To be clear, I have installed .NET core.

**Comment by davidjenni** [comment]
@Laskewitz I wonder if that has to do how your dotnetCore is setup? On my MBP, running macOS Big Sur 11.4 and dotnetCore 5.0.300, pac runs.
- can you check what your dotnet version is and on what path? The error message "file /Users/<alias>/dotnet does not exist" is a tad odd. On my mac (running fish, but also tried with zsh and bash), I get:
```
$ which dotnet
/opt/homebrew/bin/dotnet
$ dotnet --version
5.0.300
```
- there is a workaround: disable telemetry for now:
```
$ pac telemetry disable
```

**Comment by ArsyMus** [comment]
I have the same issue.
