### ISSUE TITLE
pac modelbuilder - Static const Fields class missing Virtual fields

### ISSUE THREAD

**Issue by daryllabar** [microsoft/powerplatform-vscode#509]
For Related Entities, there is a virtual field that can be used to filter the primary name column of the entity, without having to explicitly join to the the table.  In the example below, the column "acme_unitofmeasurename" is a virtual column that should be added to the latebound consts Fields class generation.

``` C#
    var query = new QueryExpression("acme_inventory")
    {
        ColumnSet = new ColumnSet("acme_location", "acme_unitofmeasure"),
    };
    query.Criteria.AddCondition("acme_unitofmeasurename", ConditionOperator.Equal, "EACH");
```

**Comment by MattB-msft** [comment]
We have decided to include this feature in the next release. it will be an "opt in" feature and also include accessors for the formatted values associated with the properties when populated.

**Comment by MattB-msft** [comment]
This was picked up in Version: 1.25.2+g1c4a1b8 of CLI
