### ISSUE TITLE
pac solution import / export operations shows random % complete when using async flag

### ISSUE THREAD

**Issue by dylanhaskins** [microsoft/powerplatform-vscode#511]
Hi Team,

When using pac solution import with --async the progress results show a % complete value which is not a true value. It shows a very low % value and usually ends at some random percentage between 1 and 10.

![image](https://user-images.githubusercontent.com/14045980/233520285-dc1dcce7-7c2e-4f3d-a14e-d041eac801b1.png)

**Comment by tehcrashxor** [comment]
The phrasing is not really clear here, but that percentage is not a work-done percentage, but a percentage of the max wait time before pac times out.   The Dataverse services don't provide any information about the progress of the task other than "running, failed, complete", so it's not possible for pac to give a reasonable work-done percentage.

**Comment by dylanhaskins** [comment]
Thanks @tehcrashxor , the percentage makes much more sense now :) 

For reference though, the statement around Dataverse services not providing information about progress, is not entirely true. Async solution import jobs do provide a progress indicator. Solution Upgrade jobs don't though.

Prior to wanting to use the pac solution import (as we use many of the other pac cli tools too) we were using the ImportSolutionToCrmAsync method of the CrmServiceClient which returns a .progress property. Just FYI ;) 


Polling Import for Solution: WSDTBase : In Progress - 90.58%
Polling Import for Solution: WSDTBase : In Progress - 90.58%
Polling Import for Solution: WSDTBase : In Progress - 90.58%
Polling Import for Solution: WSDTBase : In Progress - 90.78%
Polling Import for Solution: WSDTBase : In Progress - 90.78%
Polling Import for Solution: WSDTBase : In Progress - 90.78%
Polling Import for Solution: WSDTBase : In Progress - 90.98%
Polling Import for Solution: WSDTBase : In Progress - 91.38%
Polling Import for Solution: WSDTBase : In Progress - 91.58%
Polling Import for Solution: WSDTBase : In Progress - 92.38%
Polling Import for Solution: WSDTBase : In Progress - 92.79%
Polling Import for Solution: WSDTBase : In Progress - 92.99%
Polling Import for Solution: WSDTBase : In Progress - 100.00%
Polling Import for Solution: WSDTBase : Succeeded - 100.00%
Applying Upgrade to Solution
Async Operation ID: f9e99cb7-e0bb-ed11-83fe-00224818a66b
Polling Promotion status for Solution: WSDTBase : In Progress
Polling Promotion status for Solution: WSDTBase : In Progress
Polling Promotion status for Solution: WSDTBase : In Progress

**Comment by tehcrashxor** [comment]
PAC uses the DatverseServiceClient's [ImportSolutionAsync(...)](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/44a1af6fca8e9b3ec806d2322fbceab332b3164e/src/GeneralTools/DataverseClient/Client/Extensions/DeploymentExtensions.cs#L392), which returns an Async Operation ID.
We then poll over [GetEntityDataByID("asyncoperation", jobId, ...)](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/44a1af6fca8e9b3ec806d2322fbceab332b3164e/src/GeneralTools/DataverseClient/Client/Extensions/QueryExtensions.cs#L500), but that response does not have any progress property.
