### ISSUE TITLE
pac paportal download --overwrite throw exception

### ISSUE THREAD

**Issue by awong789** [microsoft/powerplatform-vscode#52]
When using the --overwrite option to download powerportal code, it throws exception as below.
I tried to run VS Code in admin mode, still same issue

![image](https://user-images.githubusercontent.com/5443445/120068058-0f6e3000-c0c2-11eb-83f1-a3a9b5c1d95d.png)

**Comment by ameyaapte1** [comment]
Hey! The overwrite flag expects a bool string along with it, eg. '-o true', '--overwrite true'
Will create a bug to handle the error gracefully and check if it's possible to set it true when the argument is passed

**Comment by awong789** [comment]
Thank you!
