### ISSUE TITLE
Error   PA3003: Parse error: Property should be at same indent level

### ISSUE THREAD

**Issue by AhmedAbuelaish** [microsoft/powerplatform-vscode#53]
Formatting in vs code drops the indentation in line 350 of the .yaml file. 
When packing the source files it throws a PA3003: Parse error

using the command **_>pac canvas pack ..._**

```
348        Text: |-
349            ="Click the blue Save disk in the top left to submit a Rapid Response or to save any changes.
350
351            Incident Classification:
352            Light - <4 hrs
353            Serious - >4 & <24hrs"
```
![image](https://user-images.githubusercontent.com/42521688/120875134-de817580-c56f-11eb-862a-29c11f5c39c2.png)

**Comment by davidjenni** [comment]
unless there is a current repro, the latest canvas libraries in pac CLI do have addressed this error. If anyone still has a repro, please provide a repro with a .msapp that stil shows this error in pac CLI v1.12.2 or the upcoming Feb refresh, v1.13.x
