### ISSUE TITLE
Error message: Cannot install Power Pages generator

### ISSUE THREAD

**Issue by wd21sos** [microsoft/powerplatform-vscode#545]
I just installed the Power Platform Tools and everytime when I open VS Code this error occurs:
_Cannot install Power Pages generator: Error: spawnSync npm.cmd ENOENT_

When I want to preview an HTML file it does not generate it correctly. 

Current version: v1.1.27

![image](https://github.com/microsoft/powerplatform-vscode/assets/92533241/0dfe1bfe-2b0c-4844-85c6-4ef5ba473609)

**Comment by tehcrashxor** [comment]
This error indicates that the extension was not able to start the NPM process to install the Power Pages Generator package, which typically means that NPM is not installed on the machine or otherwise not found in the PATH.

@amitjoshi438 is looking into this via internal bug AB#3349472

**Comment by amitjoshi438** [comment]
Hi @wd21sos 
Please ensure that you have Node and NPM installed on your machine. Will enhance the error handling to make it actionable.

**Comment by wd21sos** [comment]
That was the issue. NPM was not installed. Thx

**Comment by wd21sos** [comment]
That was the issue. NPM was not installed. Thx
