### ISSUE TITLE
Please use the VSCode language for pac

### ISSUE THREAD

**Issue by brasov2de** [microsoft/powerplatform-vscode#57]
Even if the windows is not in english (german in my case), a lot of devs prefer all the development tools in english.
We need to do demos in english too.

Unfortunatelly the "Power Platform VS Code extension" gets installed in german. Is there a way to change the language?
Using the VSCode language as a base for the installation would be great too.

**Comment by davidjenni** [comment]
@brasov2de and I discussed offline: setting Windows display language does achieve what Diana needs. Resolving for now

**Comment by brasov2de** [comment]
Thank you @davidjenni  ! 
Yes, after changing  "Windows display language" and also the regional format and keyboard (as we discussed offline) I have an english "pac cli" and Windows environment, but it works without issues.
![2021-06-15 20_42_05-Clipboard](https://user-images.githubusercontent.com/29977935/122106480-42325b00-ce1a-11eb-9026-72e02f9cc657.png)
Thanks again for your support!
Kind regards,
Diana
