### ISSUE TITLE
Pac solution delete request timed out waiting for reply after 00:04:00

### ISSUE THREAD

**Issue by RajeevPentyala** [microsoft/powerplatform-vscode#608]
While triggering 'pac solution delete --solution-name' for a moderately sized solution, encountered the following error. Could you please advise if there is a way to increase the timeout setting or suggest a better solution to handle this?

_[ '' ]
##[error]error: 1
##[error]failed: Connected to... SEFA Dev 3
Connected as ***

Deleting Dataverse Solution...
Microsoft PowerPlatform CLI
Version: 1.23.3+ga05f0df

Error: The request channel timed out while waiting for a reply after 00:04:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
    The HTTP request to 'https://sefa-dev-3.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.3165' has exceeded the allotted timeout of 00:04:00. The time allotted to this operation may have been a portion of a longer timeout.
        The operation has timed out_

**Comment by petrochuk** [comment]
in version 1.25 we changed the default timeout of 4 minutes to 30 of DataverseServiceClient (which PAC CLI uses internally).

This can also be changed in .config file:

```xml
    <appSettings>
	  <add key="MaxDataverseConnectionTimeOutMinutes" value="30"/>
    </appSettings>
```
