### ISSUE TITLE
Live preview icon shows as empty 

### ISSUE THREAD

**Issue by nick6262** [microsoft/powerplatform-vscode#64]
When using VScode the preview icon just shows an empty square. I thought I hadn't got the setup correct and was wondering why it wasn't there. 

It still works when you click on it. 

![image](https://user-images.githubusercontent.com/85934371/122033905-e2f82a80-cdc8-11eb-990d-47ffbad103d7.png)

**Comment by ashishchoudhary001** [comment]
Hey @nick6262, thanks for trying the extension and pointing out the issue. We had noticed this immediately after our release and fix for the same will be rolled out with the June release (expected soon!).

I will keep the bug open till we verify this with the coming release.

**Comment by ashishchoudhary001** [comment]
Hey @nick6262, we have released a new version of the extension - v0.2.10. Please do check it out. This version has a fix for the preview icon issue.
