### ISSUE TITLE
dotnet tool pac in Actions

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-vscode#643]
pac auth with -env switch does not seems to work inside Actions.

![image](https://github.com/microsoft/powerplatform-vscode/assets/5035266/dd356d61-2f26-4141-b31f-6b097e17e510)

The error seems to be coming from DataverseServiceClient.

![image](https://github.com/microsoft/powerplatform-vscode/assets/5035266/e9c3686a-fb09-40fc-ac05-8e17ccd3465a)

The credentials are correct. What is causing this?

**Comment by rajyraman** [comment]
Auth with -u (Dataverse) works, but -env (Universal) does not. Same AppId and Secret.

![image](https://github.com/microsoft/powerplatform-vscode/assets/5035266/4ba751ec-c0e4-4521-b9be-6c37c1694249)

**Comment by rajyraman** [comment]
I am finished up with my repo and I plan to record this next week. Please have a look at https://github.com/rajyraman/PowerApps-Managed-Identity-Demo-Functions/blob/main/hooks/postprovision.ps1#L9 for the workaround I am using because of this pac issue.

Can you please help @petrochuk or @kkanakas?

**Comment by petrochuk** [comment]
When you say:
> pac auth with -env switch does not seems to work inside Actions.

Do you mean `pac auth create`? Your screenshot shows `pac admin assign-user`. Can you add command that doesn't work or set of repro steps for us to try?

**Comment by rajyraman** [comment]
@petrochuk - Normally after you create the auth profile you'll see the URL of the environment which is not shown here.

![pac auth env clientid secret](https://github.com/microsoft/powerplatform-vscode/assets/5035266/08d48ae5-eff4-4583-8636-f9eca01d092b)

Same for Managed Identity as well.

![pac auth managed identity](https://github.com/microsoft/powerplatform-vscode/assets/5035266/9e59fa41-15b4-4aa4-938c-ebdd1864b778)

So even though it says connections are created, that it is usable.
