### ISSUE TITLE
Fulfilled 6.0.0 requirement preventing pac installation in Power Platform Tools for Visual Studio Code on Mac

### ISSUE THREAD

**Issue by zwhitchcox** [microsoft/powerplatform-vscode#670]
[Power Platform Tools for Visual Studio Code](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction#install-using-power-platform-tools-for-visual-studio-code) is complaining that I don't have dotnet v 6.0.0 or greater installed, when it is installed:

<img width="895" alt="Screenshot 2023-08-15 at 10 24 42 AM" src="https://github.com/microsoft/powerplatform-vscode/assets/4328800/b9f7679a-3e94-41ee-8107-4eea0fa2e6af">
I've tried installing the x64 and amd64 versions (on an M2) and uninstalling later versions (7.0.4 and 7.110.0), and I get the same error.

Not sure where to go from here.

**Comment by petrochuk** [comment]
Take a look at these [Troubleshoot .NET tool usage issues](https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues) some are specific to MacOS

**Comment by zwhitchcox** [comment]
Ok, I figured it out.

I just needed to close VS Code completely and reopen it. Apparently it holds the dotnet version somewhere in memory, and when you close all windows, it does not reset the version. You have to actually quit VS Code and reopen it after you install the dotnet tools.

Not sure if you want to leave this open in case you want to check for the installed version instead of keeping it in memory. I guess it could be an environment variable too, not sure. Feel free to close this though.

For people searching:
```
Cannot install pac cli dotnet sdk 6.0 or greater must be installed mac os x power apps
```
