### ISSUE TITLE
Power Platform CLI (PAC) for PowerShell?

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/powerplatform-vscode#68]
Do you know if there are plans to release a PowerShell version of PAC (e.g. a set of cmdlets that expose the same functionality as the existing PAC)?

Thanks,
Ben

**Comment by davidjenni** [comment]
the pac CLI architecture does provide for wrapping its noun/verbs into PsCmdlet, but we currently have no committed plan to release such a PS module.
For now, the engineering team is focusing on adding more core functionality to the pac CLI itself and also expose some of that in form of CI/CD tasks and actions, all based on the pac CLI.
CC: @kkanakas

**Comment by bgribaudo** [comment]
Thanks, @davidjenni.

Do you know if there are plans to open source the pac CLI tool (thinking maybe a community contribution could add the PowerShell wrapping...)?

**Comment by kkanakas** [comment]
@bgribaudo, we are evaluating options to Open source the PAC CLI, but initially we may not accept contributions, but it will evolve from there

CC:@davidjenni

**Comment by bgribaudo** [comment]
Thank you, @kkanakas!

**Comment by jannickoeben** [comment]
Please consider using Crescendo as a wrapper.
https://github.com/PowerShell/Crescendo
https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-3/
