### ISSUE TITLE
Update to latest version of Power Platform CLI

### ISSUE THREAD

**Issue by Chris-WP** [microsoft/powerplatform-vscode#69]
The latest version of Power Platform CLI showing on Nuget is currently v1.7.4

Does the extension automatically update to the latest version of the CLI?

My terminal window within VSCode seems to still be showing v1.7.2

**Comment by davidjenni** [comment]
@Chris-WP the pac CLI 1.7.2 and 1.7.4 are fully equivalent, and no new features or bug fixes are in 1.7.4.
We did 2 hotfixes to the PCF npm modules pcf-scripts, and since we sim-ship pac CLI and PCF modules, the CLI got incremented.
