### ISSUE TITLE
Error message when using power portal on VSCode

### ISSUE THREAD

**Issue by Jamaal1997** [microsoft/powerplatform-vscode#737]
When I open my connected portals app on VSCode it comes up with this error message but I do not understand or know the reason as to why the message appears. Below is the message  

"Cannot install Power Pages generator: Error: spawnSync npm.cmd ENOENT"

**Comment by Setnour6** [comment]
I had the same problem. Installing node.js solved that problem for me

**Comment by ashishchoudhary001** [comment]
@amitjoshi438 this is coming because of installing yeoman generator. Please check if we can show an error message which is more intuitive.

**Comment by amitjoshi438** [comment]
Updated the error msg.
