### ISSUE TITLE
Power-fx Repl: Ctrl-C doesn't exit cleanly

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#750]
I'm not able to exit from Power-Fx repl using Ctrl-C

![image](https://github.com/microsoft/powerplatform-vscode/assets/6078398/9daa23ed-d60a-4c86-a170-4c4f0a56bf68)

I'm using PowerShell 5 in Windows terminal
![image](https://github.com/microsoft/powerplatform-vscode/assets/6078398/bd6df920-0fac-4582-8b69-687299659cc5)

I have to close the terminal window

**Comment by rajyraman** [comment]
+1. I cannot even type any Power Fx expression in REPL. It is just stuck.

**Comment by snizar007** [comment]
Thanks for your feedback. To exit from the REPL, use Exit() function with capital 'E'.

**Comment by BetimBeja** [comment]
I have the same issue. The terminal is frozen and accepts no commands. I even tried to type the command without having the feedback, but it is just stuck there.

**Comment by BetimBeja** [comment]
I can use `pac power-fx run --file filename --echo True`, but `pac power-fx repl` freezes. I tried creating an environment in the US but it is the same.

https://github.com/microsoft/powerplatform-vscode/assets/11160171/81bae6ab-3951-4710-b30c-42a886e0ac25

**Comment by snizar007** [comment]
> I can use `pac power-fx run --file filename --echo True`, but `pac power-fx repl` freezes. I tried creating an environment in the US but it is the same.
> 
>  Power-FX.REPL.mp4

Hi @BetimBeja - Can you try using "`pac power-fx run --file filename --echo" without True?
Also, make sure you have PAC CLI version 1.28 installed.
Let me know or DM me.

Thanks,
ShafQat

**Comment by BetimBeja** [comment]
@snizar007 `--echo` works correctly without specifying the True value
![image](https://github.com/microsoft/powerplatform-vscode/assets/11160171/8724569c-2d3d-4d4a-9f5e-020f1af6d2d8)

The REPL issue was solved when installing `pac` as a dotnet tool. Or using the `vscode` extension. I only have the issue with the `MSI` version.

**Comment by snizar007** [comment]
Glad to have this working for you. Closing the issue.
