### ISSUE TITLE
'pac canvas download' command failing with "No auth profiles were found on this computer" error

### ISSUE THREAD

**Issue by RajeevPentyala** [microsoft/powerplatform-vscode#793]
Even though the authentication profile created and available, 'pac canvas download' command keep throwing "No auth profiles were found on this computer" error. Please refer the screenshot below.

![image](https://github.com/microsoft/powerplatform-vscode/assets/104883923/c46497c8-5379-449a-a176-58ee9c3c0173)

**Comment by snizar007** [comment]
Hi,
I see you are using auth type (DATAVERSE). Can you try to do the same steps with auth type (*UNIVERSAL)?

You may also want to take a look at this blog: https://devblogs.microsoft.com/powerplatform/power-platform-cli-simplifying-authentication-profiles/
