### ISSUE TITLE
Setting environment values (organizationsettings) isn't supported by solution pack operation.

### ISSUE THREAD

**Issue by sergeytunnik** [microsoft/powerplatform-vscode#797]
Version
```shell
>pac help
Microsoft PowerPlatform CLI
Version: 1.29.11+g9e2b163
``` 
Steps to reproduce:
1. Add setting environment value into solution.
![image](https://github.com/microsoft/powerplatform-vscode/assets/512079/012316b5-d7ee-46c9-9823-093eeaea82d9)
2. Export solution and unpack zip file to verify that setting environment value is present inside.
```│   customizations.xml
│   solution.xml
│   [Content_Types].xml
│
└───organizationsettings
    └───AsyncOnSave
            organizationsetting.xml
```
3. Unpack solution using pac to verify that setting environment value is properly unpacked.
Command: `pac solution unpack -z .\tunnikev_1_0_0_1.zip -f .\out-1`
```
├───organizationsettings
│   └───AsyncOnSave
│           organizationsetting.xml
│
└───Other
        Customizations.xml
        Solution.xml
```
4. Pack solution using pac and verify if that setting environment values is present inside zip.
Command: `pac solution pack -f .\out-1 -z .\tunnikev_1_0_0_1-out-1.zip`
```
    customizations.xml
    solution.xml
    [Content_Types].xml

No subfolders exist
```

NB
Having setting environment values inside solutions is properly supported by Dataverse and we can verify it by changing value and reimporting solution exported at step 2. We can then see that it is overwritten to the values we have in solution zip files.
Seems like just solution packager tool doesn't fully support that type of customizations.

References:
- https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-edit-configure-settings
- https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/get-update-setting-value-using-code
- https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/savesettingvalue?view=dataverse-latest

**Comment by tehcrashxor** [comment]
Fixed with last week's PAC v1.31.6 release.
