### ISSUE TITLE
Add alternate output formats to PAC CLI to enable automated use

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#81]
PAC CLI output is human readable format, which makes pac difficult to use in other scripts and github actions, e.g.

https://github.com/microsoft/powerplatform-actions/blob/7bbd803800dd4d35eb8d8aa5b132404d25df043d/src/actions/create-environment/index.ts#L27

It would be good to have something along the lines of Azure CLI, e.g. https://www.thomasmaurer.ch/2020/06/how-to-configure-azure-cli-default-output-format/

**Comment by davidjenni** [comment]
it is on our backlog, but no ETA yet
