### ISSUE TITLE
BUG: pac auth create for GCC doesn't select right cloud 

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-vscode#972]
I am in version 1.32.8 and it seems like running `pac auth create`, doesn't select the right GCC cloud by default. Currently it defaults to 'Public'. I believe in past, it used to automatically select 'UsGov' when we used the command.

**Comment by tehcrashxor** [comment]
`pac auth create` without any arguments will always (and has always) targeted the Public cloud.
PAC can figure out the right cloud if you pass your organization's URL to the `--environment` command, but otherwise would need a `--cloud` argument to specify explicitly.
